// Print-optimized leadership report. Hidden on screen, shown only in print (see index.css).
// Always light-themed for a clean printed / PDF output regardless of the app's dark UI.
import type { CohortSummary } from "../engine/types";
import type { Analytics } from "../lib/analytics";

function Stat({ label, value, sub }: { label: string; value: string | number; sub?: string }) {
  return (
    <div style={{ border: "1px solid #e2e8f0", borderRadius: 8, padding: "10px 12px" }}>
      <div style={{ fontSize: 10, textTransform: "uppercase", letterSpacing: ".04em", color: "#64748b", fontWeight: 700 }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 800, color: "#0f172a", lineHeight: 1.1 }}>{value}</div>
      {sub && <div style={{ fontSize: 11, color: "#64748b" }}>{sub}</div>}
    </div>
  );
}

const th: React.CSSProperties = { textAlign: "left", padding: "7px 10px", fontSize: 10, textTransform: "uppercase", letterSpacing: ".03em", color: "#64748b", borderBottom: "2px solid #e2e8f0", fontWeight: 700 };
const td: React.CSSProperties = { padding: "6px 10px", fontSize: 12, color: "#334155", borderBottom: "1px solid #eef0f4" };
const tdR: React.CSSProperties = { ...td, textAlign: "right", fontVariantNumeric: "tabular-nums" };

export function ReportView({ cohort, analytics, grievanceCount }: { cohort: CohortSummary; analytics: Analytics; grievanceCount: number }) {
  const pct = (x: number) => `${Math.round((x / cohort.total) * 100)}%`;
  const topReds = cohort.results.filter((s) => s.flag === "Red").sort((a, b) => b.riskScore - a.riskScore).slice(0, 18);
  const today = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  return (
    <div style={{ background: "#ffffff", color: "#0f172a", fontFamily: "Inter, system-ui, sans-serif", maxWidth: 800, margin: "0 auto", padding: 8 }}>
      {/* header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", borderBottom: "2px solid #0b1120", paddingBottom: 14 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <img src="/sst-logo.png" alt="SST" style={{ width: 44, height: 44, objectFit: "contain" }} />
          <div>
            <div style={{ fontSize: 20, fontWeight: 800 }}>Student Success Report</div>
            <div style={{ fontSize: 12, color: "#64748b" }}>Scaler School of Technology · Term 2</div>
          </div>
        </div>
        <div style={{ textAlign: "right", fontSize: 12, color: "#64748b" }}>
          <div style={{ fontWeight: 700, color: "#334155" }}>{today}</div>
          <div>Generated by SSTProgs</div>
        </div>
      </div>

      {/* summary */}
      <h2 style={{ fontSize: 13, fontWeight: 800, margin: "20px 0 10px" }}>Cohort summary</h2>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10 }} className="break-avoid">
        <Stat label="Students" value={cohort.total} sub={`${analytics.byBatch.length} batches`} />
        <Stat label="High (Red)" value={cohort.red} sub={pct(cohort.red)} />
        <Stat label="Medium (Amber)" value={cohort.amber} sub={pct(cohort.amber)} />
        <Stat label="Low (Green)" value={cohort.green} sub={pct(cohort.green)} />
        <Stat label="Avg attendance" value={`${analytics.kpi.avgAtt}%`} />
        <Stat label="Avg grade" value={analytics.kpi.avgGrade} />
        <Stat label="Failing (≥1)" value={analytics.kpi.failing} />
        <Stat label="Grievances" value={grievanceCount} />
      </div>

      {/* by batch */}
      <h2 style={{ fontSize: 13, fontWeight: 800, margin: "22px 0 8px" }}>Risk by batch</h2>
      <table style={{ width: "100%", borderCollapse: "collapse" }} className="break-avoid">
        <thead>
          <tr>
            <th style={th}>Batch</th><th style={{ ...th, textAlign: "right" }}>Students</th><th style={{ ...th, textAlign: "right" }}>Red</th><th style={{ ...th, textAlign: "right" }}>Amber</th><th style={{ ...th, textAlign: "right" }}>Green</th><th style={{ ...th, textAlign: "right" }}>Avg Att</th><th style={{ ...th, textAlign: "right" }}>Avg Grade</th><th style={{ ...th, textAlign: "right" }}>Failing</th>
          </tr>
        </thead>
        <tbody>
          {analytics.byBatch.map((b) => (
            <tr key={b.batch}>
              <td style={{ ...td, fontWeight: 700, color: "#0f172a" }}>{b.batch}</td>
              <td style={tdR}>{b.total}</td>
              <td style={{ ...tdR, color: "#dc2626", fontWeight: 700 }}>{b.Red}</td>
              <td style={{ ...tdR, color: "#b45309" }}>{b.Amber}</td>
              <td style={{ ...tdR, color: "#15803d" }}>{b.Green}</td>
              <td style={tdR}>{b.avgAtt}</td>
              <td style={tdR}>{b.avgGrade}</td>
              <td style={tdR}>{b.failing}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* by subject */}
      <h2 style={{ fontSize: 13, fontWeight: 800, margin: "22px 0 8px" }}>Subject performance</h2>
      <table style={{ width: "100%", borderCollapse: "collapse" }} className="break-avoid">
        <thead>
          <tr>
            <th style={th}>Subject</th><th style={{ ...th, textAlign: "right" }}>Enrolled</th><th style={{ ...th, textAlign: "right" }}>Avg Att</th><th style={{ ...th, textAlign: "right" }}>Avg Grade</th><th style={{ ...th, textAlign: "right" }}>Pass rate</th>
          </tr>
        </thead>
        <tbody>
          {analytics.subjects.map((s) => (
            <tr key={s.subject}>
              <td style={{ ...td, color: "#0f172a" }}>{s.subject}</td>
              <td style={tdR}>{s.enrolled}</td>
              <td style={tdR}>{s.avgAtt}</td>
              <td style={tdR}>{s.avgGrade}</td>
              <td style={tdR}>{s.passRate}%</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* interventions */}
      <h2 style={{ fontSize: 13, fontWeight: 800, margin: "22px 0 8px" }}>Intervention workload to schedule</h2>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10 }} className="break-avoid">
        {analytics.interventions.map((i) => (
          <div key={i.name} style={{ border: "1px solid #e2e8f0", borderRadius: 8, padding: "10px 12px" }}>
            <div style={{ fontSize: 12, color: "#334155", fontWeight: 600 }}>{i.name}</div>
            <div style={{ fontSize: 18, fontWeight: 800, color: "#4f46e5" }}>{i.Mandatory}<span style={{ fontSize: 11, color: "#94a3b8", fontWeight: 500 }}> mandatory</span></div>
            {i.Optional > 0 && <div style={{ fontSize: 11, color: "#64748b" }}>+ {i.Optional} optional</div>}
          </div>
        ))}
      </div>

      {/* highest risk */}
      <h2 style={{ fontSize: 13, fontWeight: 800, margin: "22px 0 8px" }}>Highest-risk students (top {topReds.length})</h2>
      <table style={{ width: "100%", borderCollapse: "collapse" }}>
        <thead>
          <tr>
            <th style={th}>Student</th><th style={th}>Batch</th><th style={{ ...th, textAlign: "right" }}>Risk</th><th style={th}>Concern areas</th>
          </tr>
        </thead>
        <tbody>
          {topReds.map((s) => (
            <tr key={s.id}>
              <td style={{ ...td, fontWeight: 700, color: "#0f172a" }}>{s.id}</td>
              <td style={td}>Batch {s.batch}</td>
              <td style={{ ...tdR, fontWeight: 700, color: "#dc2626" }}>{s.riskScore}</td>
              <td style={{ ...td, fontSize: 11, color: "#64748b" }}>{s.concerns.join(", ")}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ marginTop: 24, paddingTop: 12, borderTop: "1px solid #e2e8f0", fontSize: 10, color: "#94a3b8" }}>
        SSTProgs · Scaler SST Student Success · Generated {today}. Risk model: attendance/academics/remedial/engagement weighted-deficit index; Red at score ≥ {50} or 2+ fails, Amber at ≥ 35.
      </div>
    </div>
  );
}
